export enum ICONS {
  hamburger = 'hamburger',
  search = 'search',
  google = 'google',
  microphone = 'microphone',
  clock = 'clock',
  chevronDown = 'chevron-down',
  edit = 'edit',
  mail = 'mail',
  phone = 'phone',
  menu = 'menu',
  equalizer = 'equalizer',
  plus = 'plus',
  shoppingBag = 'shopping-bag',
  settings = 'settings',
  notification = 'notification',
  logOut = 'log-out',
  check = 'check',
  person = 'person',
  chevronLeft = 'chevron-left',
  eye = 'eye',
  eyeOff = 'eye-off',
  heart = 'heart',
  trash = 'trash',
}
