export default Object.freeze({
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',

  MAIN_TABS_ROOT: 'MAIN_TABS_ROOT',
  MAIN_DRAWER_ROOT: 'MAIN_DRAWER_ROOT',

  //Auth Stacks
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  FORGOT_PASSWORD_SCREEN: 'FORGOT_PASSWORD_SCREEN',

  MY_CART_SCREEN: 'MY_CART_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
  PRODUCT_DETAIL_SCREEN: 'PRODUCT_DETAIL_SCREEN',

  // STACKS
  AUTH_STACK: 'AUTH_STACK',
  HOME_STACK: 'HOME_STACK',
  FAVORITE_STACK: 'FAVORITE_STACK',
  MY_CART_STACK: 'MY_CART_STACK',

  ALERT: 'ALERT', // Do not redirect!
});
